import Head from "next/head";
import React, { useEffect } from "react";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// function to calculate time countdown string
function formatDate(date) {
  var delta = Math.abs(new Date() - date);
  var days = Math.floor(delta / (1000 * 60 * 60 * 24));
  var hours = Math.floor((delta % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((delta % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((delta % (1000 * 60)) / 1000);
  console.log(days, hours, minutes, seconds);
  return [
    days > 0 ? days + " dias " : "",
    hours > 0 ? hours + " horas " : "",
    minutes > 0 ? minutes + " minutos " : "",
    seconds > 0 ? seconds + " segundos " : "",
  ].join("");
}
const dateInFuture = new Date("2022-10-01");

export default function Home() {
  const [time, setTime] = React.useState(formatDate(dateInFuture));

  useEffect(() => {
    setTimeout(() => {
      setTime(formatDate(dateInFuture));
    }, 1000);
  }, [time]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="#">{time}</a>
        </h1>
      </main>
    </div>
  );
}
